# Generated by Django 3.1.2 on 2020-11-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0002_decisao_opcao_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='opcao',
            field=models.CharField(max_length=255, verbose_name='Opção'),
        ),
    ]
