# Generated by Django 3.1.2 on 2020-11-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0003_auto_20201107_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='nome',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opcao',
            name='opcao',
            field=models.CharField(max_length=10, verbose_name='Opção'),
        ),
    ]
