# Generated by Django 3.1.2 on 2020-11-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0005_auto_20201108_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinicaoSimulacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='opcao',
            name='formula',
            field=models.CharField(default=1, max_length=1000, verbose_name='Fórmula'),
            preserve_default=False,
        ),
    ]
