# Generated by Django 3.1.2 on 2020-11-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0006_auto_20201109_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predefinicaosimulacao',
            options={'ordering': ('id', 'nome'), 'verbose_name': 'Predefinição de simulação', 'verbose_name_plural': 'Predefinicações de simulações'},
        ),
        migrations.AddField(
            model_name='predefinicaosimulacao',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
