# Generated by Django 3.1.2 on 2020-11-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0007_auto_20201109_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='sexo',
        ),
        migrations.AddField(
            model_name='participante',
            name='dados',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
