# Generated by Django 3.1.2 on 2020-11-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0008_auto_20201109_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='predefinicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ambiente.predefinicaosimulacao'),
            preserve_default=False,
        ),
    ]
