# Generated by Django 3.1.2 on 2020-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0010_auto_20201109_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='icone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
