# Generated by Django 3.1.2 on 2020-11-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0011_opcao_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='direcao',
            field=models.CharField(blank=True, choices=[('C', 'Cima'), ('D', 'Direita'), ('B', 'Baixo'), ('E', 'Esquerda')], max_length=1, null=True, verbose_name='Direcao'),
        ),
    ]
