# Generated by Django 3.1.2 on 2020-11-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0013_auto_20201109_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='direcao',
            field=models.CharField(blank=True, choices=[('C', 'Cima'), ('D', 'Direita'), ('B', 'Baixo'), ('E', 'Esquerda'), ('DC', 'Decisão')], max_length=2, null=True, verbose_name='Direcao'),
        ),
    ]
