# Generated by Django 3.1.2 on 2020-11-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0017_predefinicaosimulacao_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='direcao',
            field=models.CharField(blank=True, choices=[('C', 'Cima'), ('D', 'Direita'), ('B', 'Baixo'), ('E', 'Esquerda'), ('F', 'Fim'), ('DC', 'Decisão')], max_length=2, null=True, verbose_name='Direcao'),
        ),
    ]
