# Generated by Django 3.1.2 on 2020-11-14 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0018_auto_20201113_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaAmbiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.IntegerField()),
                ('mapa', models.TextField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiente.ambiente')),
            ],
            options={
                'verbose_name': 'Mapa ambiente',
                'verbose_name_plural': 'Mapas ambientes',
                'ordering': ('id', 'ambiente', 'versao'),
            },
        ),
    ]
