# Generated by Django 3.1.2 on 2020-11-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0019_mapaambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='atividade',
            field=models.CharField(max_length=255, verbose_name='Atividade'),
        ),
    ]
