# Generated by Django 3.1.2 on 2020-11-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0021_atividade_sequencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='sequencia',
            new_name='atividade_anterior',
        ),
        migrations.AddField(
            model_name='atividade',
            name='proxima_atividade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
