# Generated by Django 3.1.2 on 2020-11-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0024_auto_20201122_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='decisao_falsa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Decisão Falsa'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='decisao_verdadeira',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Decisão verdadeira'),
        ),
    ]
