# Generated by Django 3.1.2 on 2020-11-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0026_auto_20201123_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='Fórmula'),
        ),
    ]
