# Generated by Django 3.1.2 on 2020-11-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0027_auto_20201123_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='atividade_anterior',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Atividade Anterior'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='proxima_atividade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Próxima atividade'),
        ),
    ]
